dist: trusty
sudo: false
language: node_js
node_js: node
cache: yarn

deploy:
  provider: npm
  email:
    secure: be2k1une3LO1uRjfqTgA1uMjJNUXyYsLrlx7vZpITrhSj7oqVMihrg4J4Ro/Zff1H5ka2zPs8zvx5C61vZ4uG9oPAstJV4vEaAAJZMwdewnJXNcD6HTIGacwTrKL5Ja87KtCUTzqPlOVuI8SCWWi+qEZ21nozmmau0CXm+SwtIbJ3LglEyB+BUT//KlvsrFXRu3ZJzEC3xhZDKS9YmEks3wGIZ67Mgb+VKt1s/4rsZ1TXrq4kE3aBGZLm0SMVVvjE5Xq1j9ALLu2qxgo9EMBalH0Mgk08kw05sv7qk6ia1GCXU/YjrnDBrVAKtLkFHrYtVmwX/B5LkGv9NWSiPwRxpOHx9GpwEMLPohDlXo0jF4RQOPTjH6rJ2bqC3GDkHESlYvzFaro19RnDrKCDvnqj8VRJowuedOe6edezal8sfOoDq9bMla2BlhlwcUlzk4FwyiXr/9jW6+FS9hRfIYp5ioD9pcnajJatwCIUgbjCPJiYtHngsYclBQ4IuIY/v3wZtcPS1/zrpNKzIFKwXLuWnV79CMcKhhwztHBrkv9BKlImMoV8I/LLhgsupVdG4pbHNka8ui4XrQc0ZGUalNQZMVg4XEeDspeOTdV66RID6jUdO0OW3FPMXuNptUOopgu6YwbVpCqVfqXlPhUn5bSPXO9LgL3Revd4vgP8EHeKIQ=
  api_key:
    secure: mEwFicpT9fcHO4K0KdRbF8/HIyZ2zBW19TBMdLDIVh2oie+/yXVrXGRHRr2XO1i4jK/oUfrU5gfx2PXTAQlwFdvunLGB5igHhEPBswxHxkSXgCqgxlfyxfLmLk2ibCVsPHzOWmQLfowWJHny1oMBhKCLyVJv0/t+44VezKBvdAonO1jJu6uvc1SYD+bFuGHCUV1MdKF5bYfO22HPwutvfFkg9nwjhwPPCbuwDbrqdEdgL+X4TCiD5/kQa540UrJpfVxTscqkeyx41ZJYd8I8lIgLAKfUtMBP17yoZAxK+cujoxUGY5ACjqQErYesJDa75hz582ORonIN5q1YXB/VYTdhjTmhtiGqM3lrQFtEUw5/QGjcHh2d3CSr1lDx9URy/Az2FB55ZAsC0GxCxV32653VGzck3Sg+ns+JuQgUf3n3Kqq6y7UrGhPSaRIZGg/LvmbpoQYaw9GrtHlmd8ebGFufHglYn2KSL05EGvsthq2icZnKNQdw3PEDG+kIxN7DAeElMKz2zRnT1FwXiQL9EWjakA6StbL+V+fj6LVNig6AOgiXw+DSlCmszZyVywwHx0kH41Fmw0UEBHpMOvS3hYN8PHwpOQcR7bIp/6a8E9bXjZWLevMEhRjn0simSO7XVazrx5ZCdhd/CWj9fFEj6htRWaksPm9ts/wvA4Lzt/Y=
  on:
    tags: true
